version: '3.5' 

services:
  # Watchtower (docker container updater)
  # This container polls every 5 minutes for updates to docker containers.
  # I.E. Auto updates the tools for you, no need to manually update containers. 
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - darknet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - URL=brandontalbot.com
      - SUBDOMAINS=www,radarr,sonarr,plex,emby,netdata,ombi,sabnzbd,hydra,lidarr
      - VALIDATION=http
      - EMAIL=bjtal91@gmail.com
    volumes:
      - ${CONFIG_DIR}/nginx/:/config

  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    hostname: brandontalbot.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - darknet
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  emby: 
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    networks:
      - darknet
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/emby:/config
      - ${SERIES_DIR}:/media/Series
      - ${MOVIES_DIR}:/media/Movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    environment: 
      - AUTO_UPDATES_ON=true
      - UID=${UID}
      - GID=${GID}
  
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${SERIES_DIR}:/media/Series
      - ${MOVIES_DIR}:/media/Movies
      - ${MUSIC_DIR}:/media/Music
      - ${TRANSCODE_DIR}:/transcode
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - VERSION=docker

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    networks:
      - darknet
    volumes:
      - ${CONFIG_DIR}/ombi:/config
    ports:
      - 3579:3579
    environment:
      - PUID=${UID}
      - PGID=${GID}

  sonarr: 
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    networks:
      - darknet
    volumes: 
      - ${CONFIG_DIR}/sonarr:/config
      - ${SERIES_DIR}:/tv
      - ${COMPLETE_DIR}:/downloads
    environment:
      - UID=${UID}
      - GID=${GID}

  radarr: 
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    networks:
      - darknet
    volumes: 
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${COMPLETE_DIR}:/downloads
    environment:
      - UID=${UID}
      - GID=${GID}

  lidarr: 
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    networks:
      - darknet
    volumes: 
      - ${CONFIG_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${DOWNLOADS_DIR}:/downloads
    environment:
      - UID=${UID}
      - GID=${GID}

  sabnzbd: 
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - darknet
    volumes: 
      - ${CONFIG_DIR}/sabnzbd:/config
      - ${INCOMPLETE_DIR}:/incomplete-downloads
      - ${COMPLETE_DIR}:/downloads
    environment:
      - UID=${UID}
      - GID=${GID}

  hydra:
    image: linuxserver/hydra2
    container_name: hydra
    restart: unless-stopped
    networks:
      - darknet
    volumes: 
      - ${CONFIG_DIR}/hydra:/config
      - ${COMPLETE_DIR}:/downloads
    environment:
      - UID=${UID}
      - GID=${GID}

  website:
    image: com.brandontalbot/website:latest
    container_name: website
    restart: unless-stopped
    networks:
      - darknet
    environment:
      - PUID=1000
      - PGID=1000
  
networks:
  darknet:
    name: darknet
